package SampleDaoModel;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.database.Database;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import SampleDaoModel.Person;
import SampleDaoModel.Address;
import SampleDaoModel.Book;

import SampleDaoModel.PersonDao;
import SampleDaoModel.AddressDao;
import SampleDaoModel.BookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig addressDaoConfig;
    private final DaoConfig bookDaoConfig;

    private final PersonDao personDao;
    private final AddressDao addressDao;
    private final BookDao bookDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        addressDaoConfig = daoConfigMap.get(AddressDao.class).clone();
        addressDaoConfig.initIdentityScope(type);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        addressDao = new AddressDao(addressDaoConfig, this);
        bookDao = new BookDao(bookDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(Address.class, addressDao);
        registerDao(Book.class, bookDao);
    }
    
    public void clear() {
        personDaoConfig.getIdentityScope().clear();
        addressDaoConfig.getIdentityScope().clear();
        bookDaoConfig.getIdentityScope().clear();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public AddressDao getAddressDao() {
        return addressDao;
    }

    public BookDao getBookDao() {
        return bookDao;
    }

}
